### ISSUE TITLE
app for ability bias

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoApps#3]
take the mincer setup

```
y = b0 + b1 x + (g0 + g1 A) s + u
s = a0 + g1 A + a1 Z + e
```

where all coefs are non-negative, A is N(0.5,0.25^2) truncated at zero and one, Z ~ N(0,1) truncated at [-2,2] and x is a bernoulli with p=0.4. both u and e are N~(0,1) uncorrelated.

A is unobserved to the econometrician.

## app outputs

* two-panel plot. left panel shows scatter of (s,y), right shows (z,s). each with a fitted regression line.
* `ggplot(data, aes(x = s, y = y, color = A)) + geom_point()`
* we want to show that the true effect of s on y is b2 and that we confound s and A if we don't have something like an IV. the result of `biased = lm( y ~ x + s )` does not recover `b2`. 
* output a table

coef | true | estimate
----|-----|------
b2 | number | `coef(biased)[3]`

* output a second table where we instrument for s with Z. you can run `estimatr::iv_robust` for example. you do 
```
iv <- estimatr::iv_robust(y ~ x + s | x + Z, data)
```
    

when you have a slider on `a1`

### app inputs

1. slider for a1 : strenth of the instrument

**Comment by dxy99999** [comment]
Here I come across a question.  It seems that if we generate the s, A from a bivariate normal distribution with a specific rho. Then we could not assign z to be uniform since they have a constrain `s = a0 + a1 z + A + e`. In other words, a uniform z here may be a very weak iv with no correlation with s and A, so the a1 is tend to be zero.

What I think now is that we generate z and A with U[0,1] and N(0,1). Then set the coefficient a0, a1 to get z. And then we can get a correlated s and A. The cons for this method is that we cannot directly predict the empirical rho between s and A. But their theoretical rho can be computed.

**Comment by dxy99999** [comment]
Here is a compute for the rho, it seems the analytical result is not very complicated. 
$$
Cov(s,A)=Cov(a_0+a_1z+A+e,A)=Cov(A,A)=Var(A)
$$
$$
\rho^2=\frac{Cov(s,A)^2}{Var(s)Var(A)}=\frac{Var(A)}{Var(s)}=\frac{\sigma_A^2}{a_1\sigma_z^2+\sigma_e^2+\sigma_A^2}=\frac{1}{a_1+2}
$$

**Comment by dxy99999** [comment]
It seems like the rho is strictly positive since the coefficient of A is 1. If we can manipulate the coefficient of A then we can get the negative rho. :-)

**Comment by floswald** [comment]
additional restriction: `b3 = a1`

**Comment by floswald** [comment]
hi @dxy99999 , you were right, the model i wrote down is not suitable for this exercise. I had tried to modify a more complex example, but it does not work well in this context. i edited the description and notation again (sorry!) above. i also pushed a script with 2 functions that implement most of what you need. I think you could almost paste in to your `server` function and run it to get data and estimation outputs. the results are starkest with `run(alpha)` where `alpha \in [0,2]`, so i would put that range on the slider. you can grab the code here in the `models.R` file.

https://github.com/ScPoEcon/ScPoApps/tree/fo/ability/inst/shinys/Ability_Bias

( i just saw there might be a `library(data.table)` missing in that script :smile:)
