### ISSUE TITLE
illustrate marginal effects of probit/logit models

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoApps#4]
## background

this app relates to this chapter in our book https://scpoecon.github.io/ScPoEconometrics/binary.html

this should illustrate why there is no single *marginal effect* in a probit model. that is while in the linear model

```
dy / dx_i = \beta_i
```

in the nonlinear probit/logit case we have

```
d Pr(y_i = 1 | x) / dx_i = g(x\beta) \beta_i 
```
where `g` is the pdf of the chosen cdf `G` (standard normal for probit, logistic for logit)

that is: the marginal effect depends not only on  \beta_i but at which `x` you choose to evaluate that expression. In this app we assume for simplicity that \beta = 1.

## Output of app

something like this plot:

```
library(ggplot2)
ggplot(data.frame(x = c(-5,5)), aes(x=x)) + 
  stat_function(fun = pnorm, aes(colour = "Probit")) + 
  stat_function(fun = plogis, aes(colour = "Logit")) + 
  theme_bw() + 
  scale_colour_manual(name = "Function G",values = c("red", "blue")) +
  scale_y_continuous(name = "Pr(y = 1 | x)")
```

![Screenshot 2020-09-08 at 09 12 31](https://user-images.githubusercontent.com/1021558/92444627-77d35500-f1b3-11ea-9b91-674fbdd6fb3d.png)

(but for one case at a time)

where you add a straight tangent line illustrating the slope at a certain value of `x`. 

### app input

* dropdown menu : logit vs probit
* slider: x \in [-3,3]. this value is evaluated in g(x). you draw a straight line through point (x,G(x)) (put a marker there), with slope g(x).

**Comment by floswald** [comment]
not sure ggplot is the best way to achieve this btw. maybe with base R you are better off eg.

```
curve( expr = pnorm, from,to)
# compute start and end points, given x and above formula (x0,x1 etc)
segment(x0 = x0,x1=x1,y0=y0,y1=y1)
```

**Comment by floswald** [comment]
looks perfect to me. let's talk about submitting this via PR next time we talk. thanks!

**Comment by xinyu-daidai** [comment]
No problem! I am learning more git skills and keep working on the rest APPs!

**Comment by floswald** [comment]
@dxy99999 you know what would be really cool here to add: in the box on the left where you have the slider, just at the bottom, a text output that gives the current value of the derivative. in your code, you would just display the value of `tangent`. can you add that please?

**Comment by xinyu-daidai** [comment]
Sure, no problem!
