### ISSUE TITLE
.onLoad failed in loadNamespace() for 'broom'

### ISSUE THREAD

**Issue by michelefioretti** [ScPoEcon/ScPoApps#6]
Hi, I installed the `ScPoApps` as by the readme file running

```
if (!require(devtools)) {install.packages("devtools"); library(devtools)}
install_github(repo = "ScPoEcon/ScPoApps")

```
and updated all the packages that need update.  Then when I load the package I get the following error:

```
library(ScPoApps)
Error: package or namespace load failed for ‘ScPoApps’:
 .onLoad failed in loadNamespace() for 'broom', details:
  call: get0(oNam, envir = ns)
  error: lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/backports/R/backports.rdb' is corrupt
In addition: Warning message:
In get0(oNam, envir = ns) : internal error -3 in R_decompress1
```

I tried in two different machines, the error stays. Could you help me with that please?

**Comment by floswald** [comment]
it's weird because the word `broom` does not appear in the entire repo. like if someone used `library(broom)` without adding the dependency. please reopen if it comes back
